### ISSUE TITLE
Support to other third parties

### ISSUE THREAD

**Issue by augustocdias** [lalitmee/cobalt2.nvim#1]
Would you consider adding support to the other following third party plugins:

[LSP Diagnostics](https://neovim.io/doc/user/lsp.html)
[LSP Trouble](https://github.com/folke/lsp-trouble.nvim)
[Barbar](https://github.com/romgrk/barbar.nvim)
[Lightspeed](https://github.com/ggandor/lightspeed.nvim/blob/main/COLORSCHEMES.md)

And also to [cmp lsp kinds](https://github.com/hrsh7th/nvim-cmp/pull/584) for colouring the auto complete items?

```
CmpItemKindText 
CmpItemKindMethod
CmpItemKindFunction 
CmpItemKindConstructor
CmpItemKindField
CmpItemKindVariable
CmpItemKindClass 
CmpItemKindInterface 
CmpItemKindModule
CmpItemKindProperty
CmpItemKindUnit 
CmpItemKindValue 
CmpItemKindEnum 
CmpItemKindKeyword
CmpItemKindSnippet
CmpItemKindColor
CmpItemKindFile 
CmpItemKindReference
CmpItemKindFolder 
CmpItemKindEnumMember
CmpItemKindConstant
CmpItemKindStruct
CmpItemKindEvent 
CmpItemKindOperator 
CmpItemKindTypeParameter 
CmpItemAbbrDeprecated 
CmpItemAbbrMatch
CmpItemAbbrMatchFuzzy
```

**Comment by lalitmee** [comment]
@augustocdias, you can track satus here:

- [x] [LSP Diagnostics](https://neovim.io/doc/user/lsp.html)
- [ ] [LSP Trouble](https://github.com/folke/lsp-trouble.nvim)
- [ ] [Barbar](https://github.com/romgrk/barbar.nvim)
- [ ] [Lightspeed](https://github.com/ggandor/lightspeed.nvim/blob/main/COLORSCHEMES.md?rgh-link-date=2022-02-25T13%3A15%3A51Z)
- [x] [nvim-cmp](https://github.com/hrsh7th/nvim-cmp)

**Comment by lalitmee** [comment]
@augustocdias, the support for the mentioned third parties is added. :fire: 

Enjoy.
