### ISSUE TITLE
The cursor is really hard to see

### ISSUE THREAD

**Issue by augustocdias** [lalitmee/cobalt2.nvim#3]
I find the cursor really hard to see as well as the text inside it... Could you set to something more clear?

![image](https://user-images.githubusercontent.com/1080789/155949193-99381ab2-69db-4ec0-8273-0e6d7228e274.png)

**Comment by lalitmee** [comment]
@augustocdias, are you on the latest commit because I am able to see the `cursor` very clearly in every situation.

![cobalt2_cursor_issue](https://user-images.githubusercontent.com/10762218/156099137-acd9dc75-61f1-4c7d-a067-7e89938d1a8f.gif)

And from your screenshot, I also don't understand what mode you are in.

I would recommend that you update the plugin and then see if it works or not.

**Comment by augustocdias** [comment]
Yes I'm on latest commit and it is normal mode.

**Comment by lalitmee** [comment]
Then, I think it should work. Check your cursor settings in neovim.

**Comment by augustocdias** [comment]
After the color settings the only I call in my setup are key maps and which key.

**Comment by lalitmee** [comment]
Did you try with the minimal config? comment every other plugin but `cobalt2.nvim` and then check if it's working. And it would be better if you can check the highlight of the cursor somehow. I use `Telescope highlights`.

**Comment by augustocdias** [comment]
Even with minimal I'm having the same issue...

![image](https://user-images.githubusercontent.com/1080789/156184059-b9aa356c-a41a-4a89-a216-c83dc1ba6e76.png)

Here's the minimal I've used:

```lua
local on_windows = vim.loop.os_uname().version:match('Windows')

local function join_paths(...)
    local path_sep = on_windows and '\\' or '/'
    local result = table.concat({ ... }, path_sep)
    return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir
if on_windows then
    temp_dir = vim.loop.os_getenv('TEMP')
else
    temp_dir = '/tmp'
end

local fn = vim.fn

vim.cmd('set packpath=' .. join_paths(temp_dir, 'nvim', 'site'))

local package_root = join_paths(temp_dir, 'nvim', 'site', 'pack')
local install_path = join_paths(package_root, 'packer', 'start', 'packer.nvim')
local compile_path = join_paths(install_path, 'plugin', 'packer_compiled.lua')

fn.system({
    'git',
    'clone',
    '--depth',
    '1',
    'https://github.com/wbthomason/packer.nvim',
    install_path,
})

require('packer').startup({
    {
        'wbthomason/packer.nvim',
        { 'lalitmee/cobalt2.nvim', requires = 'tjdevries/colorbuddy.nvim' },
    },
    config = {
        package_root = package_root,
        compile_path = compile_path,
    },
})

require('packer').sync()
require('colorbuddy').colorscheme('cobalt2')
```

**Comment by lalitmee** [comment]
@augustocdias, I have kept the cursor color the same as it shows in the cobalt2 theme of `vscode` which is by `wesbos`. Now I am not sure what is happening with your config.

Have you set cobalt2 theme in your terminal too?

**Comment by augustocdias** [comment]
No. Not in the terminal

**Comment by lalitmee** [comment]
@augustocdias, were you able to find out the issue?

**Comment by augustocdias** [comment]
No. Not yet.

**Comment by lalitmee** [comment]
Hey @augustocdias, if you still have this issue, let me know. 

Although, I am pretty sure that there should be something in your config which is setting your cursor color or something to the cursor.

Let me know if you figure it out.

**Comment by augustocdias** [comment]
I haven't been using it. I never found the reason why it was acting like that... :( 

I guess you can just close this issue

**Comment by lalitmee** [comment]
Thanks for updating.
