### ISSUE TITLE
Not rendering correct characters in the barbar

### ISSUE THREAD

**Issue by augustocdias** [lalitmee/cobalt2.nvim#4]
In the bufferline from barbar, the characters from unactive buffers are not being shown correctly:

Print from other theme (tokyonight):
![image](https://user-images.githubusercontent.com/1080789/155949772-1124ce48-1683-45fb-bf9a-51171a4fa2ed.png)

Print from cobalt2:

![image](https://user-images.githubusercontent.com/1080789/155949873-c261598c-c766-4a3c-aab2-2e22db0d78f8.png)

**Comment by lalitmee** [comment]
@augustocdias, I am not sure if this is the problem of color scheme. I think it is the font you are using for `italic`. That is not the proper `nerd font` and that also doesn't look `Fira Code Italic` to me.

For me, it's working fine.

![barbar_cobalt](https://user-images.githubusercontent.com/10762218/156099862-b13d3234-6d42-44dd-89f2-0788f1e513c5.png)

See if you can set some font which is a nerd font.

**Comment by augustocdias** [comment]
yes, you're right. I'm using alacritty and it allows to set different fonts for normal and italic. It was set to an unpatched victor mono font.
