### ISSUE TITLE
Bufferline, Lualine and Cursor 

### ISSUE THREAD

**Issue by AbbasSrour** [lalitmee/cobalt2.nvim#5]
Hey, first thanks for the cobalt2 port I really enjoyed this colorscheme back when I used Code. On dashboard the statusline seems to be white, same as the bufferline, and the cursor. 
![2022 03 01-20 55 44 screenshot](https://user-images.githubusercontent.com/17765628/156231260-4d5fb4ed-346b-4c1a-b3f7-2b9cc7705875.png)

**Comment by lalitmee** [comment]
I am guessing that you are using [this](https://github.com/glepnir/dashboard-nvim) dashboard plugin?

**Comment by AbbasSrour** [comment]
Ahh my mistake, I should have specified, I'm using alpha plugin.

**Comment by AbbasSrour** [comment]
The problem is that I tried what you said and it didn't work
> When I ran this command it appeared as expected. Basically swapping `yellow` with `cobalt_bg`
> 
> ```
> :lua require("cobalt2.utils").Group.new("Cursor", require("cobalt2.utils").colors.cobalt_bg, require("cobalt2.utils").colors.yellow, nil)
> ```
>

**Comment by AbbasSrour** [comment]
Ok thanks gonna take look at my plugins.
