### ISSUE TITLE
It's really awesome, except when "set cursorline" and "set cursorcolumn"

### ISSUE THREAD

**Issue by tan-wei** [lalitmee/cobalt2.nvim#6]
The cursor is yellow, and it's OK. But if we enable cursor line and cursorcolum, it comes:
![图片](https://user-images.githubusercontent.com/28227509/173105082-75f2006d-e3e3-4ae9-9191-bf0b5fea2924.png)

Is there any work around? Thanks!

**Comment by lalitmee** [comment]
Are you on the latest version?

**Comment by tan-wei** [comment]
OK, I think I find the prolem. There's "another" `cobalt2` in a colorscheme collection. I should workaround with it. Thanks for your reply.

**Comment by tan-wei** [comment]
And the colorscheme is awesome!
