### ISSUE TITLE
Is it possible to remove italic style

### ISSUE THREAD

**Issue by VladPetriv** [lalitmee/cobalt2.nvim#7]
Is it possible to remove italic style from this theme?
It'll be nice to have this option

**Comment by lalitmee** [comment]
@VladPetriv, Actually right now we don't have the config to remove that. But I think you can override that using something like this.
```lua
local c = require("colorbuddy.color").colors
local Group = require("colorbuddy.group").Group

Group.new("Comment", c.blue, nil, nil)
```

Can you try this?

**Comment by VladPetriv** [comment]
>Can you try this?

Yes it's work fine. That's why I've closed an issue. But thanks)
