### ISSUE TITLE
Explain theme variables

### ISSUE THREAD

**Issue by thieung** [lalitmee/cobalt2.nvim#8]
Hi @lalitmee,

Thanks for your nice config, I'm currently reference your config in order to write my own config. I'm very interested in your colorscheme system.

Could you please share what is the meaning of your pallets? Such as base16 (https://github.com/chriskempson/base16/blob/main/styling.md) or base46 (https://github.com/NvChad/base46#understanding-theme-variables)

**Comment by lalitmee** [comment]
Hello @thieung,

If you are asking about the file `palette.lua` then I would say that its just a file with all the color names and values in it. And I think not all the colors are being used in the colorscheme as far as I remember. So if you are creating your own `colorscheme`, then just define the `colors`, `names` and `values` somewhere in a file which you can maintain easily.

Let me know if you need any more help.

Thanks

**Comment by thieung** [comment]
Thanks for your feedback @lalitmee , I will try first then will ask you if need help :)

**Comment by thieung** [comment]
Hi @lalitmee 
In case I apply new colorscheme and follow your palette recipe,  with my main colors (blue, yellow, red), how do I know what is the hex code for something like darker, darkest, ...? Is that 10% darker compared to main color?



<img width="698" alt="image" src="https://user-images.githubusercontent.com/79964592/194746117-3bdbeaa0-d6b5-46f1-bf19-b4a3b02b6260.png">

**Comment by lalitmee** [comment]
Hi @thieung, actually I got this `palette` directory from the official repo of [cobalt2](https://github.com/wesbos/cobalt2). I would suggest you can read more about the color's selection there.
